# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
url: "https://anthbrtn.com" # the url of your github pages

# site information used in page title, meta data etc.
title: "Anthony Burton"
description: "Internet culture researcher"

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Anthony Burton
author-bio: "I’m a Mellon-SFU Fellow at the Digital Democracies Institute, working on my dissertation about the relationship between “theory”, intelligence, desire, and mimesis in contemporary “late fascist” politics.

My most recent work is Algorithmic Authenticity, which investigates the role that authenticity plays in contemporary information disorders. Fact-checking’s effectiveness is one of the fictions at the core of liberal democracy. Trump’s entire sideshow shtick notwithstanding, the idea usually ran that journalists just got the facts right when politicians occasionally lied. That’s not true, and the emergence of populist forms of threat with tenuous relationships to the truth isn’t historical news either. In response to this moment, we looked at the concept of algorithmic authenticity as a vector for these questions surrounding truth, fact, and digital subjecthood. You can find a copy, open access, here."  # change to false to hide
author-image: ams.jpg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: {{site.url}}/about
- text: Presentations
  permalink: presentations
- text: Publications
  permalink: publications
- text: Algorithmic Authenticity
  permalink: "https://meson.press/books/algorithmic-authenticity/"
- text: Contact
  permalink: contact

  # use false to turn off any social media links
twitter: https://twitter.com/anthbrtn
facebook: false
instagram: false
github: https://gitlab.com/anthbrtn
linkedin: false
medium: false
oogle-scholar: https://scholar.google.com/citations?user=FxoLSjYAAAAJ&hl=en&inst=10441630620217902552
email: false

# footer information
#footer-msg: "Powered by Tailpages"
#footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
#google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
