# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
url: "https://anthbrtn.com" # the url of your github pages

# site information used in page title, meta data etc.
title: "Anthony Burton"
description: "Internet culture researcher"

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Anthony Burton
author-bio: "I’m a Mellon-SFU Fellow at the Digital Democracies Institute, working on my dissertation about the relationship between “theory”, intelligence, desire, and mimesis in contemporary “late fascist” politics."
author-image: ams.jpg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Presentations
  permalink: presentations
- text: Publications
  permalink: publications
- text: Algorithmic Authenticity
  permalink: "https://meson.press/books/algorithmic-authenticity/"
- text: Contact
  permalink: contact

  # use false to turn off any social media links
twitter: https://twitter.com/anthbrtn
facebook: false
instagram: false
github: https://gitlab.com/anthbrtn
linkedin: false
medium: false
oogle-scholar: https://scholar.google.com/citations?user=FxoLSjYAAAAJ&hl=en&inst=10441630620217902552
email: false

# footer information
#footer-msg: "Powered by Tailpages"
#footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
#google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
